contents:
  - name: 质数表
    code: Prime_Table.cpp
  - name: 质因数与因数个数表
    code-pre: Divisor_Table.tex
  - name: Windows对拍脚本
    code: Checker_Windows.cpp
  - name: Linux对拍脚本
    code: Checker_Linux.cpp
  - name: 日期计算
    code: Day_Calc.cpp
  - name: 分数类
    code: Fraction.cpp
  - name: 火车头
    code: GCC_Optimize.cpp
  - name: 快速读入(fread)
    code: Fread.cpp
  - name: int128重载
    code: int128.cpp
  - name: Mini_Bigint
    code: Mini_Bigint.cpp
  - name: Rand
    code: Rand.cpp
  - name: Unmap_Hash
    code: Unmap_Hash.cpp
