contents:
  - name: 最短路
    directory: 最短路
  - name: 连通性
    directory: 连通性
  - name: 网络流
    directory: 网络流
  - name: 匹配
    directory: 匹配
  - name: 圆方树
    code: Block_Tree.cpp
  - name: 基环树
    code: Pseudo_Tree.cpp
  - name: 2-SAT
    code: Two_Sat.cpp
  - name: 网格图转对偶图
    code: Grid_2_Dual.cpp
  - name: 平面图转对偶图
    code: Planar_2_Dual.cpp
  - name: 无向图枚举三元环
    code: Count_Triangle.cpp
  - name: Prufer序列
    code: Prufer_Code.cpp
    code-pre: Prufer_Code-pre.tex
