contents:
  - name: 最大异或和
    code: Basis.cpp
  - name: 线性表出，方案数
    code: Basis_Count.cpp
  - name: 区间线性基
    code: Basis_Range_Count.cpp
  - name: GF(3)
    code: Basis_GF(3).cpp
  - name: 互质基
    code: Basis_Coprime.cpp
