contents:
  - name: 普通线段树
    code: segTree_old.cpp
  - name: 普通线段树-操作封装
    code: segTree_normal.cpp
  - name: 懒标记线段树-操作封装
    code: segTree_lazy.cpp
  - name: 动态开点线段树
    code: dynamic_segTree.cpp
  - name: 吉司机线段树
    code: segTree_beat.cpp
