contents:
  - name: 筛法
    directory: 筛法
  - name: 数论函数
    directory: 数论函数
  - name: 多项式
    directory: 多项式
  - name: 线性基
    directory: 线性基
  - name: 高斯消元
    directory: 高斯消元
  - name: 组合数
    code: comb.cpp
  - name: Lucas 定理
    code: Lucas.cpp
    code-pre: Lucas-pre.tex
  - name: exgcd
    code: exgcd.cpp
  - name: BSGS
    code: BSGS.cpp
    code-pre: BSGS-pre.tex
  - name: exCRT
    code: exCRT.cpp
    code-pre: exCRT-pre.tex
  - name: 二元一次不定方程
    code: xy_Function.cpp
  - name: 矩阵与行列式
    code: Matrix_and_Det.cpp
  - name: Floor_Sum
    code: Floor_Sum.cpp
    code-pre: floor_sum-pre.tex
  - name: Miller-Rabin素性检验
    code: Miller_Rabin.cpp
