contents:
  - name: 字符串哈希
    code: Hash.cpp
  - name: 二维字符串哈希
    code: Hash_2D.cpp
  - name: KMP
    code: KMP.cpp
  - name: Z-函数
    code: Z_Algorithm.cpp
  - name: Manacher
    code: Manacher.cpp
  - name: AC自动机
    code: AC_Automaton.cpp
  - name: 后缀自动机
    code: SAM.cpp
  - name: 回文自动机
    code: PAM.cpp
