contents:
  - name: Geometry_Rabbit
    code: Geometry_Rabbit.cpp
  - name: Geometry_Jiangly
    code: Geometry_Jiangly.cpp
  - name: 三维计算几何
    code: 3D_Geometry.cpp
  - name: 分数点类
    code: Point_Fraction.cpp
  - name: 三角剖分
    code: Triangulation.cpp
