contents:
  - name: 并查集
    directory: 并查集
  - name: 线段树
    directory: 线段树
  - name: 树状数组
    directory: 树状数组
  - name: 主席树
    directory: 主席树
  - name: 李超树
    directory: 李超树
  - name: 笛卡尔树
    code: Cartesian_Tree.cpp
  - name: 动态中位数（对顶堆）
    code: Dynamic_Median.cpp
  - name: 状压 RMQ
    code: Fast_RMQ.cpp
  - name: 重链剖分
    code: HLD.cpp
  - name: 莫队
    code: Mo_Algorithm.cpp
  - name: 左偏树
    code: Leftist_Tree.cpp
  - name: pbds 平衡树
    code: Balanced_Tree(with pbds).cpp
  - name: 线段树优化建图
    code: Add_Edge_with_SegTree.cpp
  - name: set 维护区间并
    code: Maintain_Seg_with_Set.cpp
  - name: ST 表
    code: Sparse_Table.cpp
