contents:
  - name: 数据结构
    directory: 01-数据结构
  - name: 树论
    directory: 02-树论
  - name: 图论
    directory: 03-图论
  - name: 动态规划
    directory: 04-动态规划
  - name: 数学
    directory: 05-数学
  - name: 字符串
    directory: 06-字符串
  - name: 计算几何
    directory: 07-计算几何
  - name: 杂项
    directory: 08-杂项
