contents:
  - name: 筛法
    directory: 筛法
  - name: 数论函数
    directory: 数论函数
  - name: 多项式
    directory: 多项式
  - name: 线性基
    directory: 线性基
  - name: 高斯消元
    directory: 高斯消元
  - name: 组合数
    directory: 组合数
  - name: 线性求逆元
    code: Linear_inv.cpp
  - name: Exgcd
    code: Exgcd.cpp
  - name: BSGS
    code: BSGS.cpp
    code-pre: BSGS-pre.tex
  - name: ExCRT
    code: ExCRT.cpp
    code-pre: ExCRT-pre.tex
  - name: 二元一次不定方程
    code: XY_Function.cpp
  - name: 矩阵与行列式
    code: Matrix_and_Det.cpp
  - name: Floor_Sum
    code: Floor_Sum.cpp
    code-pre: Floor_Sum-pre.tex
  - name: Miller-Rabin素性检验
    code: Miller_Rabin.cpp
