contents:
  - name: LCA
    directory: LCA
  - name: 树上启发式合并
    code: Dsu_On_Tree.cpp
  - name: 树的重心
    code: Centroid.cpp
  - name: 树上k级祖先
    code: Level_Ancestor.cpp
  - name: 树哈希
    code: Tree_Hash.cpp
  - name: 虚树
    code: Virtual_Tree.cpp
  - name: treeMaxPath
    code: Tree_Max_Path.cpp
  - name: 树链求交
    code: Path_Union.cpp
